version: '3.4'

services:
  db:
    image: eclipseworks.db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: eclipseworks
    ports:
      - 3308:3306
    networks:
      - eclipseworks-networks
    
  eclipseworks.api:
    image: eclipseworks.api
    build:
      context: .
      dockerfile: EclipseWorks.API\Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - eclipseworks-networks

networks:
  eclipseworks-networks:
    driver: bridge
